name: Go

on:
  workflow_dispatch:
  push:
    #  branches: [ master ]
  pull_request:
    #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.17]
        # See supported Go release schedule at https://golang.org/doc/devel/release.html
        #
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
